version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - "35432:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  api:
    container_name: api
    restart: on-failure
    depends_on:
      - postgres
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
